version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loja-frontend
    ports:
      - "4210:80"
    restart: unless-stopped
    networks:
      - loja-network

networks:
  loja-network:
    name: loja-network
    driver: bridge 